version: '3'
services:

  #################################
  # Orchestrator related services #
  #################################

  orchestrator-api:
    image: ghcr.io/reasonableai/orchestrator:latest
    container_name: orchestrator-api
    volumes:
      - ./settings.yaml:/app/settings.yaml
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://orchestrator-redis:6379/0
      - OLLAMA_URL=http://orchestrator-ollama:11434
    depends_on:
      - orchestrator-redis

  orchestrator-worker:
    image: ghcr.io/reasonableai/orchestrator:latest
    command: celery -A celery_app worker
    container_name: orchestrator-worker
    volumes:
      - ./settings.yaml:/app/settings.yaml
    environment:
      - REDIS_URL=redis://orchestrator-redis:6379/0
      - OLLAMA_URL=http://orchestrator-ollama:11434
    depends_on:
      - orchestrator-redis

  orchestrator-flower:
    image: ghcr.io/reasonableai/orchestrator:latest
    command: celery -A celery_app flower
    container_name: orchestrator-flower
    volumes:
      - ./settings.yaml:/app/settings.yaml
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://orchestrator-redis:6379/0
    depends_on:
      - orchestrator-redis

  orchestrator-redis:
    image: redis:latest
    container_name: orchestrator-redis
    ports:
      - "6379:6379"

  orchestrator-ollama:
    image: ollama/ollama:latest
    container_name: orchestrator-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama


  ########################################
  # Semantic Networks & related services #
  ########################################

  semantic_network_web:
    image: ghcr.io/reasonableai/semantic-network:latest
    ports:
      - "5000:5000"
    environment:
      - NEO4J_URI=neo4j://semantic_network_db:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=superlongsecret
      - |
        API_DOCUMENTATION=API documentation
        This API is useful for answering questions about Python coding.
    depends_on:
      - semantic_network_db

  semantic_network_db:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/superlongsecret
    ports:
      - "7687:7687"
    volumes:
      - neo4j_data:/data


  #################
  # Communicators #
  #################

  emailer:
    image: ghcr.io/reasonableai/emailer:latest
    ports:
      - "5000:5000"
    volumes:
      - ./settings.yaml:/app/settings.yaml

volumes:
  neo4j_data:
  rabbit_data:
