version: '3'
services:

# Orchestrator
  orchestrator-web:
    build: ./orchestrator
    container_name: orchestrator-web
    hostname: orchestrator-web-host
    volumes:
      - ./settings.yaml:/app/settings.yaml
    ports:
      - "5001:5000"
    environment:
      - RABBITMQ_HOST=amqp://guest:guest@my-rabbit:5672/
      - OLLAMA_URL=${OLLAMA_URL}
    depends_on:
      - my-rabbit

  orchestrator-worker:
    build: ./orchestrator
    command: celery -A celery_app worker
    container_name: orchestrator-worker
    hostname: orchestrator-worker-host
    volumes:
      - ./settings.yaml:/app/settings.yaml
    environment:
      - RABBITMQ_HOST=amqp://guest:guest@my-rabbit:5672/
      - ORCHESTRATOR_WEB_URL=http://orchestrator-web:5000
      - OLLAMA_URL=${OLLAMA_URL}
    depends_on:
      - my-rabbit

  my-rabbit:
    image: rabbitmq:3-management-alpine
    container_name: my-rabbit
    hostname: my-rabbit-host
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbit_data:/var/lib/rabbitmq

# Semantic Network
  semantic_network_web:
    image: ghcr.io/reasonableai/semantic-network:latest
    ports:
      - "5000:5000"
    environment:
      - NEO4J_URI=neo4j://semantic_network_db:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=superlongsecret
      - |
        API_DOCUMENTATION=API documentation
        This API is useful for answering questions about Python coding.
    depends_on:
      - semantic_network_db

  semantic_network_db:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/superlongsecret
    ports:
      - "7687:7687"
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
  rabbit_data:
