version: "3.9"
services:
  my-rabbit:
    image: rabbitmq:3-management-alpine
    container_name: my-rabbit
    hostname: my-rabbit-host
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbit_data:/var/lib/rabbitmq

volumes:
  rabbit_data: